###  sanity
# curl -X GET http://c006.rodeo.tacc.utexas.edu:$debugport/
GET http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB
###



###
# curl -X PUT http://c006.rodeo.tacc.utexas.edu:$debugport/$DB
PUT http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB
###

# curl -X PUT -H "$token" -H "$user" -H "$tenant" -H "$content" http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB/streams_channel_metadata
PUT http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB/streams_channel_metadata
###

# curl -X PUT -H "$token" -H "$user" -H "$tenant" -H "$content" http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB/streams_templates_metadata
PUT http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB/streams_templates_metadata
###

# curl -X PUT -H "$token" -H "$user" -H "$tenant" -H "$content" http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB/streams_alerts_metadata
PUT http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB/streams_alerts_metadata
###

# curl -X PUT -H "$token" -H "$user" -H "$tenant" -H "$content" http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB/streams_project_metadata
PUT http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB/streams_project_metadata
###

# curl -X PUT -H "$token" -H "$user" -H "$tenant" -H "$content" http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB/streams_instrument_index
PUT http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB/streams_instrument_index
###

# curl -X PUT -H "$token" -H "$user" -H "$tenant" -H "$content" http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB/streams_metrics
PUT http://c002.rodeo.tacc.utexas.edu:31404/StreamsDevDB/streams_metrics
###


### SK grant permission for user meta all operations
POST https://dev.develop.tapis.io/v3/security/user/grantUserPermission?tenant=admin
X-Tapis-Token: {{token}}
X-Tapis-User: meta
X-Tapis-Tenant: admin
Content-Type: application/json

{"user":"meta","tenant":"admin","permSpec":"meta:admin:GET,POST,PUT,PATCH,DELETE:*:*:*"}

###

### SK grant permission for user streams for all operations on StreamsDevDB
# using meta:admin token
POST https://dev.develop.tapis.io/v3/security/user/grantUserPermission?tenant=admin
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant:admin
Content-Type: application/json

{
  "user": "streams",
  "tenant": "admin",
  "permSpec": "meta:admin:GET,POST,PUT,PATCH,DELETE:StreamsDevDB:*:*"
}

###

### SK get permissions for user streams using meta:admin service token
#
GET https://dev.develop.tapis.io/v3/security/user/perms/streams?tenant=admin
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant:admin
Content-Type: application/json

###

### SK isPermitted for user streams:admin using meta:admin service token
POST https://dev.develop.tapis.io/v3/security/user/isPermitted?tenant=admin
X-Tapis-Token: {{token}}
X-Tapis-User: streams
X-Tapis-Tenant:admin
Content-Type: application/json

{"user":"streams","tenant":"admin","permSpec":"meta:admin:GET,PUT,POST,PATCH,DELETE:StreamsDevDB:*:*"}

###




