
#  getting a admin service token for meta from Tokens service with my service password
#
# curl -u "meta:{{tokPass}}" -H "Content-type: application/json" -d '{"token_tenant_id": "admin", "account_type": "service", "token_username": "meta", "access_token_ttl": 9999999}' https://dev.develop.tapis.io/v3/tokens
POST https://dev.develop.tapis.io/v3/tokens
Authorization: Basic meta {{devTokPass}}
Content-Type: application/json

{"token_tenant_id": "admin", "account_type": "service", "token_username": "meta", "access_token_ttl": 9999999, "target_site_id": "tacc"}

###  generated Date: Fri, 11 Dec 2020 19:21:15 GMT  good til April 6, 2021

# {
#   "message": "Token generation successful.",
#   "result": {
#     "access_token": {
#       "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIxZjJlMzJlOS0xZWJmLTQ2MGQtYjdmNy1jMTNhMWZmODcwZTciLCJpc3MiOiJodHRwczovL2FkbWluLmRldmVsb3AudGFwaXMuaW8vdjMvdG9rZW5zIiwic3ViIjoibWV0YUBhZG1pbiIsInRhcGlzL3RlbmFudF9pZCI6ImFkbWluIiwidGFwaXMvdG9rZW5fdHlwZSI6ImFjY2VzcyIsInRhcGlzL2RlbGVnYXRpb24iOmZhbHNlLCJ0YXBpcy9kZWxlZ2F0aW9uX3N1YiI6bnVsbCwidGFwaXMvdXNlcm5hbWUiOiJtZXRhIiwidGFwaXMvYWNjb3VudF90eXBlIjoic2VydmljZSIsImV4cCI6MTYxNzcxNDQ3NCwidGFwaXMvdGFyZ2V0X3NpdGUiOiJ0YWNjIn0.IHRhplxg1oZ2EX8SLmeqDzNry6PXzoCVnxVX7jrYB2Z9oY5getn0m3GFDbBgRDI7hfP4SNjZd5f6ctAGiNU2nAyUDYKqT6V2X6PYSjarqkh_HV764MqsWk7XwAg7FiVvvHIaawxa1PowZfUx3JzG6_fdCMOvKqLOfWOi4mPHvULgXTp2En3zZPvBL5OfH-8yVf6YaqG8mjc4rRVlRrGlEQigFifrYUuhzbEJAc1HTxX3W-G6oYGPjpt2n66-L9q2D1QWrG8cLFP1BQFQIoqpD5BH8FurH3F_yO6rLm8G4xQZLUYvqiS4Gb9RrX_frYEGXPtLQhzCqMa2ifMt3aYTwg",
#       "expires_at": "2021-04-06T13:07:54.423734+00:00",
#       "expires_in": 9999999,
#       "jti": "1f2e32e9-1ebf-460d-b7f7-c13a1ff870e7"
#     }
#   },
#   "status": "success",
#   "version": "dev"
# }


# get a password
# curl -H "X-Tapis-Token: $TOKENS_admin" -H "X-Tapis-Tenant: admin" -H "X-Tapis-User: meta" 'https://dev.develop.tapis.io/v3/security/vault/secret/service/password?tenant=admin&user=meta'
GET https://dev.develop.tapis.io/v3/security/vault/secret/service/password?tenant=admin&user=meta
X-Tapis-Token: {{token}}
X-Tapis-Tenant: admin
X-Tapis-User: meta

###

# get list of passwords
# curl -H "X-Tapis-Token: $TOKENS_admin" -H "X-Tapis-Tenant: admin" -H "X-Tapis-User: jobs" 'https://dev.develop.tapis.io/v3/security/vault/secret/list/meta/service?tenant=admin&user=jobs'
GET https://dev.develop.tapis.io/v3/security/vault/secret/list/meta/user?tenant=admin&user=meta
X-Tapis-Token: {{token}}
X-Tapis-Tenant: admin
X-Tapis-User: meta

###

# curl -X POST -H "content-type: application/json" https://dev.develop.tapis.io/v3/oauth2/tokens -d '{"username": "testuser2", "password": "testuser2", "grant_type": "password"}'
POST https://dev.develop.tapis.io/v3/oauth2/tokens
Content-Type: application/json

{"username": "testuser2", "password": "testuser2", "grant_type": "password","access_token_ttl": 9999999}
###
# {
#   "message": "Token created successfully.",
#   "result": {
#     "access_token": {
#       "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIyYmM5ODllMC02NGY4LTRhM2ItOTk5OC1mYWJkODEyYTgyOTgiLCJpc3MiOiJodHRwczovL2Rldi5kZXZlbG9wLnRhcGlzLmlvL3YzL3Rva2VucyIsInN1YiI6InRlc3R1c2VyMkBkZXYiLCJ0YXBpcy90ZW5hbnRfaWQiOiJkZXYiLCJ0YXBpcy90b2tlbl90eXBlIjoiYWNjZXNzIiwidGFwaXMvZGVsZWdhdGlvbiI6ZmFsc2UsInRhcGlzL2RlbGVnYXRpb25fc3ViIjpudWxsLCJ0YXBpcy91c2VybmFtZSI6InRlc3R1c2VyMiIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE2MTEzNTQzMDUsInRhcGlzL2NsaWVudF9pZCI6bnVsbCwidGFwaXMvZ3JhbnRfdHlwZSI6InBhc3N3b3JkIn0.wayCWkvrNn3vOVpX_QaDULbTz3IwU_OalgTpmo2ZrLiJvM1jcWGDTFpVDby3TnU-RsPLmoykk1X7YsKEZz9_LbcqUFRC8vwdyPuRNNU9RRz83cNN3TTHWVC3bcgvPly_xUerIntT9auxrNevHXw0Da2fV6KfdbQkaUKGRyZLHJJ4_pTUbT9cKPFBPEHRpQPFK2bbuX1T-HAVP7ivHTaRJ9iZhDPRk_2ljP36RPQ1h92hLydZCN4NKED8pqd8BTIhd4PjYK6s59x8M8YYlcruQdtTWsqSxug94eBOBxzTO1bfVwzuPH8SkcnZcJ9NMgR91OouAR6cYfS-MI7HFn-kMw",
#       "expires_at": "2021-01-22T22:25:05.377486+00:00",
#       "expires_in": 14400,
#       "jti": "2bc989e0-64f8-4a3b-9998-fabd812a8298"
#     }
#   },
#   "status": "success",
#   "version": "dev"
# }



# {
#   "message": "Token created successfully.",
#   "result": {
#     "access_token": {
#       "access_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJmZTVhODI5Yy0wM2JhLTQ0OWEtOGZlNC0zOTIzOTQxMDllNzEiLCJpc3MiOiJodHRwczovL2Rldi5kZXZlbG9wLnRhcGlzLmlvL3YzL3Rva2VucyIsInN1YiI6InRlc3R1c2VyN0BkZXYiLCJ0YXBpcy90ZW5hbnRfaWQiOiJkZXYiLCJ0YXBpcy90b2tlbl90eXBlIjoiYWNjZXNzIiwidGFwaXMvZGVsZWdhdGlvbiI6ZmFsc2UsInRhcGlzL2RlbGVnYXRpb25fc3ViIjpudWxsLCJ0YXBpcy91c2VybmFtZSI6InRlc3R1c2VyNyIsInRhcGlzL2FjY291bnRfdHlwZSI6InVzZXIiLCJleHAiOjE1ODg4OTI3MTksInRhcGlzL2NsaWVudF9pZCI6bnVsbCwidGFwaXMvZ3JhbnRfdHlwZSI6InBhc3N3b3JkIn0.cb0tRoFHrvHJaKTEBojHckMvunv8bzmD07vY4GJo66Ml8Cg1MyoeD_Z-Wf2Z0MdG49Rvb3MMjEc5BLHi9qzzfAIXIcNuRhrR6QLKyPnoX_IbHWWCVh7yesnH0bIZhjygsNnLVl9llcmV9fWGYPzPh8quVdJccFw2pLneqGzxe0mLI7xfFcCL_5zNYpqj2JzM17yVj6e9vKI8qDrJzAT_jZgtNepy07ujbBbQ32-nuvMiJlygbiVxJvWzbxsv87T0UcZ_wZyw5bR8ngJhenYL6WxfXz21m4gif-bElpaNrdAHMTyMvwR_l9IX366SzZe2fN5_rs7yHxFrFH2R_g3Upg",
#       "expires_at": "2020-05-07T23:05:19.943175+00:00",
#       "expires_in": 14400,  # 4 hrs
#       "jti": "fe5a829c-03ba-449a-8fe4-392394109e71"
#     }
#   },
#   "status": "success",
#   "version": "dev"
# }


