version: '3'
volumes:
   restheart-security-testdb:

services:
   restheart:
      image: softinstigate/restheart:5.4.1
      container_name: meta-restheart
      environment:
        - MONGO_URI=mongodb://dev:dev@localhost:27017/dev?authSource=admin
      depends_on:
         - mongodb
      ports:
         - "8080:8080"

   mongodb:
       image: mongo:4.2
       container_name: restheart-mongo
       volumes:
          - restheart-security-testdb:/data/db
       environment:
         - MONGO_INITDB_ROOT_USERNAME=dev
         - MONGO_INITDB_ROOT_PASSWORD=dev
         - MONGO_INITDB_DATABASE=dev
       ports:
          - "27017:27017"
