version: '2'

### Creates a named network with the default bridge driver
# The network is shared between restheart and mongodb only
# See: https://docs.docker.com/engine/userguide/networking/dockernetworks/
# See: https://docs.docker.com/engine/reference/commandline/network_create/
# networks:
#   backend:
       
### Create a permanent, named data volume
# This makes much easier to identify where the mongodb data is stored on host
# See: https://docs.docker.com/engine/userguide/containers/dockervolumes/#mount-a-shared-storage-volume-as-a-data-volume
volumes:
   restheart-security-testdb:

services:
   meta-security:
      image: tapis/metaapi:dev
      container_name: meta-tapis-security
      environment:
         - 'tapis.site.id=tacc'
         - 'tapis.meta.service.tenantBaseUrl=https://dev.develop.tapis.io/'
         - 'tapis.meta.service.skSvcURL=https://dev.develop.tapis.io/v3'
         - 'tapis.meta.service.tokenBaseUrl=https://dev.develop.tapis.io/'
         - 'TAPIS_SERVICE_PASSWORD=GZ9A9CGaTJ5MNr89BAvw2Aazw'
      depends_on:
         - restheart
#      networks:
#         - backend
      ports:
         - "18080:8080"

   restheart:
      image: tapis/tapis-meta-rh-server:dev
      container_name: meta-restheart
      depends_on:
         - mongodb
#      networks:
#         - backend
      ports:
         - "8080:8080"
      volumes:
         - './etc/restheart.yml:/opt/restheart/etc/restheart.yml:ro'
         - './etc/config.properties:/opt/restheart/etc/config.properties:ro'

# restheart:
#    image: jenkins2.tacc.utexas.edu:5000/tapis/tapis-meta-rh-core:4.1.6
#    restart: "always"
#    log_driver: json-file
#    log_opt:
#       max-size: 100m
#       max-file: "5"
#    container_name: restheart-core
#    # command: 'java -Xms2G -Xmx2G -Dfile.encoding=UTF-8  -server -jar restheart.jar etc/restheart.yml --envFile etc/config.properties'
#    command: 'java -Dfile.encoding=UTF-8  -server -jar restheart.jar etc/restheart.yml --envFile etc/config.properties'
#    ports:
#       - "8080:8080"
#    environment:
#       - 'MONGO_URI=mongodb://tapisadmin:d3f%40ult@aloe-dev08.tacc.utexas.edu:27019/?authSource=admin'
#    volumes:
#       - './etc/restheart.yml:/opt/restheart/etc/restheart.yml:ro'
#       - './etc/config.properties:/opt/restheart/etc/config.properties:ro'
#       - '/var/log/splunk/meta-security:/var/log'

#    mongodb:
#       image: tapis/mongo-singlenode:4.4.5-bionic
#       container_name: meta-singlenode-mongodb4.4.5
#       hostname: singlenode
#       volumes:
#          #      - ./.docker/mongodb/metakeyfile:/keyfiles/metakeyfile
#          - ./docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
#          - ./docker/mongodb/data/db/:/data/db/
#          - ./docker/mongodb/data/log/:/var/log/mongodb/
# #      networks:
# #         - backend
#       env_file:
#          - .env
#       environment:
#          MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#          MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
#       ports:
#          - "27017:27017"

   mongodb:
       image: mongo:4.2
       container_name: restheart-mongo
       command: --bind_ip_all
       volumes:
          - restheart-security-testdb:/data/db
#       networks:
#          - backend
       ### mongodb port must be mapped for the test to run
       ports:
          - "27017:27017"
