---
version: "3"

volumes:
  pgdata:

services:

  rabbitmq:
    image: rabbitmq:3.7.16-management
    container_name: tapis-rabbitmq
    labels:
      name: tapis-rabbitmq
    restart: on-failure
    ports:
      - '4369:4369' 
      - '5671:5671'
      - '5672:5672' 
      - '15671:15671'
      - '15672:15672'
      - '25672:25672'  

  postgres:
    image: postgres:11.4
    container_name: tapis-postgres
    labels:
      name: tapis-postgres
    restart: always
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=postgres'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      