apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f mongo-query-exporter.yml
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-exporter
  name: mongo-exporter
spec:
  ports:
    - name: "9412"
      port: 9412
      targetPort: 9412
  selector:
    io.kompose.service: mongo-exporter
status:
  loadBalancer: {}
